### ISSUE TITLE
Default API routing options

### ISSUE THREAD

**Issue by jifeon** [apsavin/bnsf#4]
How can I specify defaults for API routing. Here is it:

``` yml
- id: auth
  path: /auth
  host: localhost:1337
- id: repos
  path: /user/repos
  host: localhost:1337
```

I do not want to copy the `host` field.
